#include <iostream>
#include <regex>
#include <fstream>
#include <string>
#include <filesystem>
#include <Windows.h>
#include <sys/stat.h>
#include <thread>
#include <wininet.h>
#include <intrin.h>
#include "modules.h"
#include "user.h"
#include "Anti.h"
#include "Config.h"
#include "confuser.h"
